@base = http://localhost:8080

#################################

# @name login
POST {{base}}/api/token
Content-Type: application/json

{
	"username": "harry",
	"email": "harrybrown98@gmail.com",
	"password": "password123"
}

#################################

@token = {{login.response.body.$.token}}
@refresh_token = {{login.response.body.$.refresh_token}}
@token_type = {{login.response.body.$.token_type}}

#################################

# @name me
GET {{base}}/secret/admin
Accept: */*
Authorization: {{token_type}} {{token}}
