{
 "title": "NGINX",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "GeoIP Map",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"nginx\"}\n  | json\n  | host !~ \"registry.*\" and\n    source != \"stderr\" and latitude != \"\" and longitude != \"\""
    }
   ]
  },
  {
   "title": "nginx logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{app=\"nginx\"}\n  | json\n  | server_name !~ \"grafana.*\""
    }
   ]
  },
  {
   "title": "Other Log Aggrigations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Count",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({app=\"nginx\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests By Host",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 14, "x": 3, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (host) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    | host != \"\"\n    [$__range]\n  )\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Request Method",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (method) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    | method != \"\"\n    [$__range]\n  )\n)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Requests By Path",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (request_uri) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    | host != \"\"\n    [$__range]\n  )\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Country Code",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (cf_ipcountry) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    | cf_ipcountry != \"\"\n    [$__range]\n  )\n)",
       "legendFormat": "{{cf_ipcountry}}"
      }
     ]
    },
    {
     "title": "Requests by Referer",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (referer) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    | referer !~ \"^http(s)?://(.*\\\\.)?(hrry|harrybrwn|hryb).(com|lol|dev|me).*\"\n    [$__range]\n  )\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Log Levels",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (\n  count_over_time(\n    {app=\"nginx\"}\n    | json\n    [$__range]\n  )\n)",
       "legendFormat": "{{cf_ipcountry}}"
      }
     ]
    },
    {
     "title": "Connection Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(\n  sum_over_time(\n    {app=\"nginx\"}\n    | json\n    | connection_time != \"\"\n    | unwrap connection_time\n    [$__interval]\n  )\n)"
      }
     ]
    },
    {
     "title": "Requests by Referer",
     "type": "logs",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 84 },
     "targets": [
      {
       "expr": "{app=\"nginx\"}\n | json\n | referer != \"-\" and referer != \"\" and\n   referer !~ \"^http(s)?://(.*\\\\.)?(hrry|harrybrwn|hryb).(com|lol|dev|me).*$\"\n | line_format \"{{.method}} {{.status}} {{.request_uri}} <= {{.referer}}\"",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}