{
 "title": "Observability Meta",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Scrape Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(scrape_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "Prometheus Average Query Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(prometheus_engine_query_duration_seconds_sum[$__range]))"
    }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job) (scrape_duration_seconds{})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus Query Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_query_duration_seconds_sum[$__rate_interval]))"
    }
   ]
  },
  { "title": "Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Stored Chunk Bytes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_chunk_store_stored_chunk_bytes_total"
    }
   ]
  },
  {
   "title": "S3 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(loki_s3_request_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Loki Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "loki_cache_hits{} / loki_cache_fetched_keys{}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (route, method) (rate(loki_request_duration_seconds_sum{method!=\"gRPC\", route!=\"metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "BoltDB Shipper Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation, status_code) (rate(loki_boltdb_shipper_request_duration_seconds_sum[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Index Entries per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_index_entries_per_chunk_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Frontend Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(loki_querier_query_frontend_request_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Index Lookups per Query",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_index_lookups_per_query_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "LogQL Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(loki_logql_querystats_latency_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Chunks per Query",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_chunks_per_query_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Chunk References in Index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 61 },
   "targets": [
    { "expr": "loki_index_chunk_refs_total" }
   ]
  },
  {
   "title": "Stored Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "loki_chunk_store_stored_chunks_total"
    }
   ]
  }
 ]
}