{
 "title": "Container Registry",
 "description": "Docker container registry.",
 "tags": [
  "docker",
  "registry"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROM", "query": "prometheus" },
   { "name": "LOKI", "query": "loki" },
   {
    "name": "handler",
    "query": {
     "query": "label_values(registry_http_requests_total, handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum without (job) (rate(registry_http_requests_total{handler=~\"$handler\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_http_response_size_bytes_bucket{handler=~\"$handler\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_http_request_size_bytes_bucket{handler=~\"$handler\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "In Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum without (job) (registry_http_in_flight_requests{handler=~\"$handler\"})"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{type=\"Hit\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{type=\"Miss\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{type=\"Request\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(\r\n    registry_storage_cache_total{type=\"Hit\"}[$__rate_interval]\r\n) /\r\nignoring (type) rate(\r\n    registry_storage_cache_total{type=\"Miss\"}[$__rate_interval]\r\n)"
    }
   ]
  },
  {
   "title": "Storage Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (type) (rate(registry_storage_cache_total[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Storage Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (action, driver) (rate(registry_storage_action_seconds_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Storage Op Duration Distrobution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{type=\"logs\", service=\"registry\"}"
    }
   ]
  },
  {
   "title": "Access Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{type=\"logs\", service=\"nginx\"} | json | server_name = \"registry.hrry.dev\""
    }
   ]
  }
 ]
}