ARG FLUENTBIT_VERSION
FROM fluent/fluent-bit:${FLUENTBIT_VERSION}
COPY config/logging/fluent-bit/fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
COPY config/logging/fluent-bit/parsers.conf /fluent-bit/etc/parsers.conf
COPY config/logging/fluent-bit/streams.conf /fluent-bit/etc/streams.conf
COPY files/mmdb/GeoLite2-City.mmdb /opt/GeoLite2-City.mmdb
COPY files/mmdb/GeoLite2-City.mmdb /opt/GeoLite2-ASN.mmdb