ARG LOKI_VERSION
FROM grafana/loki:${LOKI_VERSION}
USER root
RUN apk update && \
	apk add curl
USER loki
COPY config/logging/loki.yml /mnt/local-config.yaml
CMD ["-config.file=/mnt/local-config.yaml"]