#!/bin/sh

set -eu

name="$(basename $0)"

docker compose \
  --project-directory "$(pwd)" \
  --file config/docker-compose.tools.yml \
  --ansi never                           \
  run \
    --interactive=true \
    --no-deps           \
    --rm                \
    ansible "${name}" "$@"
