#!/bin/sh

set -eu

extras=""

# Custom SSL
#extras="-v $(pwd)/config/pki/certs/ca.crt:/etc/ssl/certs/ca-certificates.crt:ro"

docker compose --ansi never run \
  --entrypoint hydra  \
  --interactive=false \
  --use-aliases       \
  --no-TTY            \
  --no-deps           \
  --rm hydra "${@:-}"
