{
 "title": "Main",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Main Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"fluentbit\", type=\"logs\"}\n  != \"an upstream response is buffered to a temporary file\"\n  | json\n  | server_name != \"grafana.harrybrwn.com\""
    }
   ]
  },
  {
   "title": "nginx logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{ job=\"fluentbit\" }\n  | json\n  | container_name =~ \"^.*nginx.*$\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{type=\"logs\"} | json"
    }
   ]
  }
 ]
}