{
 "title": "Performance Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROM", "query": "prometheus" },
   {
    "name": "cpu_mode",
    "query": {
     "query": "label_values(node_cpu_seconds_total, mode)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_boot_time_seconds, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max without (cpu) (rate(node_cpu_seconds_total{mode=\"$cpu_mode\", hostname=~\"$hostname\"}[1m]))",
     "legendFormat": "{{hostname}} {{mode}}"
    }
   ]
  },
  {
   "title": "CPU Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max without (cpu) (rate(node_cpu_seconds_total{mode=~\"iowait|idle\", hostname=~\"$hostname\"}[1m]))",
     "legendFormat": "host:{{hostname}} mode:{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (hostname) ((node_memory_MemTotal_bytes{hostname=~\"$hostname\"} - node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "read - {{hostname}} {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "write - {{hostname}} {{device}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, instance, mode) (rate(node_cpu_seconds_total{mode=\"idle\", hostname=~\"$hostname\"}[$__rate_interval])) * 1",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (hostname, instance, mode) (rate(node_cpu_seconds_total{mode=\"user\", hostname=~\"$hostname\"}[$__rate_interval])) * 1",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (hostname, instance, mode) (rate(node_cpu_seconds_total{mode=\"system\", hostname=~\"$hostname\"}[$__rate_interval])) * 1",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (hostname, instance, mode) (rate(node_cpu_seconds_total{mode=\"iowait\", hostname=~\"$hostname\"}[$__rate_interval])) * 1",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (hostname, instance, mode) (rate(node_cpu_seconds_total{mode=\"softirq\", hostname=~\"$hostname\"}[$__rate_interval])) * 1",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$__rate_interval])"
    },
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Docker Registry Storage Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(registry_storage_action_seconds_count[$__rate_interval])",
     "legendFormat": "{{driver}} - {{action}}"
    }
   ]
  },
  {
   "title": "S3 (MinIO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(minio_s3_requests_total{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "FlubentBit Records Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_records_total[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Memory Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      { "expr": "go_memstats_alloc_bytes" }
     ]
    },
    {
     "title": "Go Garbage Collection Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Go Memory Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      { "expr": "go_gc_heap_objects_objects" }
     ]
    }
   ]
  }
 ]
}