#!/bin/sh

set -eu

#htpasswd -b -B -C 10 -c config/nginx/.passwd "$@"

docker container run             \
  --rm                           \
  --volume "$(pwd):/opt/hrry.me" \
  --user "$(id -u):$(id -g)"     \
  --workdir "/opt/hrry.me"       \
  -it httpd                      \
  htpasswd                       \
    -B                           \
    "$@"

